-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-12-17 00:33:33.754

CREATE DATABASE REAL_ESTATE;

USE REAL_ESTATE;

-- tables
-- Table: MAINTANACE
CREATE TABLE MAINTANACE (
    MAINTANANCE_ID int NOT NULL,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    QUERY_STATUS BOOL NOT NULL,
    MAINTANACE_ID int NOT NULL,
    PAYMENT_DETAILS VARCHAR(777) NOT NULL,
    PHONE_NUMBER int NOT NULL,
    Marquette_Marquette_ID int NOT NULL,
    RESIDENTIALS_RESIDENT_ID int NOT NULL,
    CONSTRAINT MAINTANACE_pk PRIMARY KEY (MAINTANANCE_ID)
);

-- Table: Marquette
CREATE TABLE Marquette (
    Marquette_ID int NOT NULL,
    Residential_NAME VARCHAR(30) NOT NULL,
    Apartment_Number int NOT NULL,
    Apartment_address VARCHAR(50) NOT NULL,
    CONSTRAINT Marquette_pk PRIMARY KEY (Marquette_ID)
);

-- Table: RENTAL_DETAILS
CREATE TABLE RENTAL_DETAILS (
    RENTAL_ID int NOT NULL,
    CREDIT_DEBIT BOOL NOT NULL,
    INTERNET_BANKING BOOL NOT NULL,
    PAYMENT_DESCRIPTION VARCHAR(999) NOT NULL,
    Marquette_Marquette_ID int NOT NULL,
    CONSTRAINT RENTAL_DETAILS_pk PRIMARY KEY (RENTAL_ID)
);

-- Table: RESIDENTIALS
CREATE TABLE RESIDENTIALS (
    RESIDENT_ID int NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    RESIDENT_RENT int NOT NULL,
    Marquette_Marquette_ID int NOT NULL,
    RENTAL_DETAILS_RENTAL_ID int NOT NULL,
    CONSTRAINT RESIDENTIALS_pk PRIMARY KEY (RESIDENT_ID)
);

-- Table: VISITORS
CREATE TABLE VISITORS (
    VISITOR_ID int NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    QUERY VARCHAR(999) NOT NULL,
    Marquette_Marquette_ID int NOT NULL,
    CONSTRAINT VISITORS_pk PRIMARY KEY (VISITOR_ID)
);

-- foreign keys
-- Reference: MAINTANACE_Marquette (table: MAINTANACE)
ALTER TABLE MAINTANACE ADD CONSTRAINT MAINTANACE_Marquette FOREIGN KEY MAINTANACE_Marquette (Marquette_Marquette_ID)
    REFERENCES Marquette (Marquette_ID);

-- Reference: MAINTANACE_RESIDENTIALS (table: MAINTANACE)
ALTER TABLE MAINTANACE ADD CONSTRAINT MAINTANACE_RESIDENTIALS FOREIGN KEY MAINTANACE_RESIDENTIALS (RESIDENTIALS_RESIDENT_ID)
    REFERENCES RESIDENTIALS (RESIDENT_ID);

-- Reference: RENTAL_DETAILS_Marquette (table: RENTAL_DETAILS)
ALTER TABLE RENTAL_DETAILS ADD CONSTRAINT RENTAL_DETAILS_Marquette FOREIGN KEY RENTAL_DETAILS_Marquette (Marquette_Marquette_ID)
    REFERENCES Marquette (Marquette_ID);

-- Reference: RESIDENTIALS_Marquette (table: RESIDENTIALS)
ALTER TABLE RESIDENTIALS ADD CONSTRAINT RESIDENTIALS_Marquette FOREIGN KEY RESIDENTIALS_Marquette (Marquette_Marquette_ID)
    REFERENCES Marquette (Marquette_ID);

-- Reference: RESIDENTIALS_RENTAL_DETAILS (table: RESIDENTIALS)
ALTER TABLE RESIDENTIALS ADD CONSTRAINT RESIDENTIALS_RENTAL_DETAILS FOREIGN KEY RESIDENTIALS_RENTAL_DETAILS (RENTAL_DETAILS_RENTAL_ID)
    REFERENCES RENTAL_DETAILS (RENTAL_ID);

-- Reference: VISITORS_Marquette (table: VISITORS)
ALTER TABLE VISITORS ADD CONSTRAINT VISITORS_Marquette FOREIGN KEY VISITORS_Marquette (Marquette_Marquette_ID)
    REFERENCES Marquette (Marquette_ID);

-- End of file.

